import dynamic from "next/dynamic";
import "./globals.css";
import type { Metadata } from "next";
const App = dynamic(() => import("./App"), {
    ssr: false,
});

export const metadata: Metadata = {
    title: "Ookra Marketplace",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <App>{children}</App>
            </body>
        </html>
    );
}
